version: '3.8'

services:
  exercise-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: exercise-analysis-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=api/app.py
      - MAX_CONTENT_LENGTH=52428800
      - UPLOAD_FOLDER=uploads
      - REPORTS_FOLDER=reports
      - CONFIDENCE_THRESHOLD=0.5
      - SMOOTHING_ALPHA=0.7
    volumes:
      - ./uploads:/app/uploads
      - ./reports:/app/reports
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - exercise-network

  # Development service (optional)
  exercise-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: exercise-analysis-api-dev
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=api/app.py
      - MAX_CONTENT_LENGTH=52428800
      - UPLOAD_FOLDER=uploads
      - REPORTS_FOLDER=reports
      - CONFIDENCE_THRESHOLD=0.5
      - SMOOTHING_ALPHA=0.7
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./reports:/app/reports
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - exercise-network

networks:
  exercise-network:
    driver: bridge

volumes:
  uploads:
  reports:
  logs:
